import React from 'react';
import { PostCard } from '../components/PostCard';
import { BlogPost } from '../types';
import { Sparkles } from 'lucide-react';
import { Link } from 'react-router-dom';

interface HomeProps {
  posts: BlogPost[];
}

export const Home: React.FC<HomeProps> = ({ posts }) => {
  return (
    <div className="min-h-screen bg-slate-50 pb-20">
      {/* Hero Section */}
      <section className="bg-white border-b border-slate-200">
        <div className="container mx-auto px-4 py-16 md:py-24 text-center">
          <span className="inline-flex items-center px-3 py-1 rounded-full bg-brand-50 text-brand-700 text-sm font-medium mb-6">
            <Sparkles className="w-4 h-4 mr-2" />
            Powered by Gemini 2.5
          </span>
          <h1 className="text-4xl md:text-6xl font-bold text-slate-900 mb-6 font-serif tracking-tight">
            Ideas amplified by <span className="text-transparent bg-clip-text bg-gradient-to-r from-brand-600 to-indigo-600">Intelligence</span>
          </h1>
          <p className="text-lg md:text-xl text-slate-600 max-w-2xl mx-auto mb-10 leading-relaxed">
            Discover insightful articles generated by AI, or create your own masterpieces in seconds. The future of blogging is here.
          </p>
          <div className="flex justify-center gap-4">
            <Link to="/create" className="bg-brand-600 text-white px-8 py-3.5 rounded-xl font-semibold hover:bg-brand-700 transition-colors shadow-lg hover:shadow-brand-500/25">
              Start Generating
            </Link>
          </div>
        </div>
      </section>

      {/* Posts Grid */}
      <main className="container mx-auto px-4 py-16">
        <div className="flex items-center justify-between mb-8">
          <h2 className="text-2xl font-bold text-slate-900 font-serif">Latest Articles</h2>
        </div>

        {posts.length === 0 ? (
          <div className="text-center py-20 bg-white rounded-3xl border border-dashed border-slate-300">
            <div className="w-16 h-16 bg-slate-100 rounded-full flex items-center justify-center mx-auto mb-4">
              <Sparkles className="w-8 h-8 text-slate-400" />
            </div>
            <h3 className="text-xl font-semibold text-slate-900 mb-2">No posts yet</h3>
            <p className="text-slate-500 mb-6">Be the first to generate an amazing article using AI.</p>
            <Link to="/create" className="text-brand-600 font-medium hover:underline">Create your first post &rarr;</Link>
          </div>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
            {posts.map((post) => (
              <PostCard key={post.id} post={post} />
            ))}
          </div>
        )}
      </main>
    </div>
  );
};
